const BUBBLE_CHILD_PROCESS_PID = 'bubble_child_process_pid'
const SSHSTARTWATCHINFO = 'SSHSTARTWATCHINFO' 
const TRYSSHSTARTWATCHINFO = 'TRYSSHSTARTWATCHINFO' 
const BROWSER_SEND_BUBBLE_STOP = 'BROWSER_SEND_BUBBLE_STOP'
const BROWSER_SEND_NODE_INIT = 'BROWSER_SEND_NODE_INIT'
const BROWSER_SEND_QUERYNODEINFO = 'BROWSER_SEND_QUERYNODEINFO'
const BROWSER_SEND_OPENPROXY = 'BROWSER_SEND_OPENPROXY'
const BROWSER_SEND_OPENDEVTOOLS = 'BROWSER_SEND_OPENDEVTOOLS' 
const BROWSER_SEND_OPENEXTERNALLINK = 'BROWSER_SEND_OPENEXTERNALLINK'
const BROWSER_SEND_UPDATEVERSION = 'BROWSER_SEND_UPDATEVERSION'
const BROWSER_SEND_STARTSSHSERVER = 'BROWSER_SEND_STARTSSHSERVER'
const BROWSER_SEND_QUERYBLSPUBKEY = 'BROWSER_SEND_QUERYBLSPUBKEY'
const BROWSER_SEND_PROXYTRANSACTION = 'BROWSER_SEND_PROXYTRANSACTION'
const BROWSER_SEND_QUERYTRY_SSHSERVERINFO = 'BROWSER_SEND_QUERYTRY_SSHSERVERINFO'
const BROWSER_SEND_SETTRYSSHINFO = 'BROWSER_SEND_SETTRYSSHINFO'


export {
    BUBBLE_CHILD_PROCESS_PID,
    SSHSTARTWATCHINFO,
    TRYSSHSTARTWATCHINFO,
    BROWSER_SEND_BUBBLE_STOP,
    BROWSER_SEND_NODE_INIT,
    BROWSER_SEND_QUERYNODEINFO,
    BROWSER_SEND_OPENPROXY,
    BROWSER_SEND_OPENDEVTOOLS,
    BROWSER_SEND_OPENEXTERNALLINK,
    BROWSER_SEND_UPDATEVERSION,
    BROWSER_SEND_STARTSSHSERVER,
    BROWSER_SEND_QUERYBLSPUBKEY,
    BROWSER_SEND_PROXYTRANSACTION,
    BROWSER_SEND_QUERYTRY_SSHSERVERINFO,
    BROWSER_SEND_SETTRYSSHINFO
}